### ISSUE TITLE
Grade Comments

### ISSUE THREAD

**Issue by aclavin-eab** [Annikizzle/Word-Guess-Game#1]
Looks great, nice organization, nice logic, great comments! The script was very easy to follow the logic of, you might want to break up your play game function into a few helper functions that play game invokes... also try to remember to remove console.logs form your code when you're done working. Some inconsistent indentation, try to remember format it properly. In the css some minor indentation and spacing inconsistency, but also you have some rules at the end of your document not applying to any specific selector... this could probably cause some issues in some contexts, like if you had other style sheets loading after that sheet or something like that. Overall very good work, coming along very nicely with javascript!

**Comment by aclavin-eab** [comment]
Oh also, as far as the actual game play goes, to me it feels a little awkward to not fill in that last letter when the game is won before you tell the user they won.

**Comment by Annikizzle** [comment]
Thanks for the input, Andrew! I was going to try and correct that last letter issue--but ran out of time. I will continue working on it over the break.
